# Generated by Django 2.2.3 on 2019-07-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='increase',
            new_name='change',
        ),
    ]
