# Generated by Django 2.2.3 on 2019-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190725_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='updated',
            field=models.BooleanField(default='False', null='true'),
            preserve_default='true',
        ),
    ]
