# Generated by Django 2.2.3 on 2019-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stocks_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('change', models.FloatField()),
            ],
        ),
    ]
