# Generated by Django 2.1.4 on 2019-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stocks_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display',
            field=models.BooleanField(default='False', null='true'),
            preserve_default='true',
        ),
    ]
