# Generated by Django 2.1.4 on 2019-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_team_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='lastprice',
            field=models.FloatField(blank='true', null='true'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(blank='true', max_length=10, null='true'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='percent',
            field=models.FloatField(blank='true', null='true'),
        ),
    ]
