# Generated by Django 2.2.4 on 2019-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stocks_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='lastprice',
            field=models.FloatField(),
        ),
    ]
