# Generated by Django 2.2.4 on 2019-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20190824_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='marketcap',
            field=models.CharField(blank='true', max_length=10, null='true'),
        ),
    ]
