# Generated by Django 2.2.4 on 2019-08-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20190825_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='marketcap',
            field=models.FloatField(blank='true', null='true'),
        ),
    ]
